name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_deploy_key

            # Ensure Git uses SSH instead of HTTPS
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git config --global url."git@github.com:".insteadOf "https://github.com/"

            # Navigate to the project folder
            cd Pediasense-API-Server

            # Pull the latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Restart the server
            pm2 restart all